version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: coffmunnity-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: coffmunnity-app
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: coffmunnity-db
    restart: always
    environment:
      MYSQL_DATABASE: coffmunnity_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: coffee_user
      MYSQL_PASSWORD: coffee_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: